This directory is generated by kubectl-anykap.

The main capture script is in `capture.py`, add more rules and tasks as
necessary.

Modify daemonset.yaml for customizing pod structure, permissions, etc.

To install and start capturing, run `kubectl apply -k .` in this directory.

For communicating with existing capture, refer to `kubectl anykap -h`.
