apiVersion: v1
kind: Pod
metadata:
  name: delayedprobe
spec:
  containers:
  - name: httpbin
    image: kennethreitz/httpbin
    readinessProbe:
      httpGet:
        port: 80
        path: "/delay/4"
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
